[Theme]
Current=gruvbox-breeze

[General]
HaltCommand=/usr/bin/systemctl poweroff
RebootCommand=/usr/bin/systemctl reboot

[Users]
MaximumUid=60513
MinimumUid=1000
RememberLastSession=true
RememberLastUser=true
ReuseSession=true

[X11]
DisplayCommand=/usr/local/bin/sddm-gruvbox-xsetup
